# Generated by Django 2.0.4 on 2018-05-03 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('LocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trippy.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SourceLocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trippy.Location')),
            ],
        ),
    ]
