# Generated by Django 2.0.4 on 2018-05-03 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippy', '0002_accomodation_transportation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='DestLocationId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Dest_transportation', to='trippy.Location'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='SourceLocationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Src_transportation', to='trippy.Location'),
        ),
    ]
