# Generated by Django 2.0.4 on 2018-05-03 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippy', '0003_auto_20180502_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlightNumber', models.IntegerField()),
                ('FlightCarrier', models.CharField(max_length=30)),
                ('MaxSeats', models.IntegerField()),
                ('CurrentSeats', models.IntegerField()),
                ('TransportId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trippy.Transportation', unique=True)),
            ],
        ),
    ]
