# Generated by Django 2.0.4 on 2018-05-03 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippy', '0004_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='id',
        ),
        migrations.AlterField(
            model_name='flight',
            name='TransportId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trippy.Transportation'),
        ),
    ]
