# Generated by Django 2.0.4 on 2018-05-03 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippy', '0005_auto_20180502_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('TransportId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trippy.Transportation')),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CarType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('TransportId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trippy.Transportation')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CruiseNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('isLeader', models.BooleanField()),
                ('GroupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trippy.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardNumber', models.IntegerField()),
                ('PaymentAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CardExpiryDate', models.DateField()),
                ('GroupLeaderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trippy.Passenger')),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='CurrentSeats',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='MaxSeats',
        ),
        migrations.AddField(
            model_name='flight',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
