# Generated by Django 2.0.4 on 2018-05-03 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippy', '0006_auto_20180502_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='Date',
            field=models.DateField(default=datetime.datetime(2018, 5, 2, 23, 20, 23, 917397)),
        ),
    ]
