# Generated by Django 2.0.4 on 2018-05-03 03:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trippy', '0007_auto_20180502_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='Date',
            field=models.DateField(default=datetime.datetime(2018, 5, 3, 3, 22, 37, 425375, tzinfo=utc)),
        ),
    ]
