# Generated by Django 2.0.4 on 2018-05-03 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trippy', '0008_auto_20180502_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
