# Generated by Django 2.0.4 on 2018-05-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippy', '0009_auto_20180502_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
