# Generated by Django 2.0.4 on 2018-05-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trippy', '0011_auto_20180502_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cruise',
            old_name='Price',
            new_name='CruisePrice',
        ),
    ]
